In [102]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import torch.optim as optim

In [103]:
df = pd.read_csv('data.csv')

In [104]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [105]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [106]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [107]:
df.shape

(569, 31)

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   diagnosis                569 non-null    object
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  569 non-null    float64
 15  smoothness_se            569 non-null    float64
 16  compactness_se           569 non-null    float64
 17  concavity_se             569 non-null    float64
 18  concave points_se        569 non-null    float64
 19  symmetry_se              569 non-null    float64
 20  fractal_dimension_se     569 non-null    float64
 21  radius_worst             569 non-null    float64
 22  texture_worst            569 non-null    float64
 23  perimeter_worst          569 non-null    float64
 24  area_worst               569 non-null    float64
 25  smoothness_worst         569 non-null    float64
 26  compactness_worst        569 non-null    float64
 27  concavity_worst          569 non-null    float64
 28  concave points_worst     569 non-null    float64
 29  symmetry_worst           569 non-null    float64
 30  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), object(1)
memory usage: 137.9+ KB

In [109]:
df['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [110]:
df.describe()

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,...,16.269190,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,...,4.833242,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,0.057700,...,13.010000,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,...,14.970000,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120,...,18.790000,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,...,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500

In [111]:
X = df.iloc[:, 1:]
y = df.iloc[:, 0]

In [112]:
X

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [113]:
X_train, X_test, y_train, y_test = train_test_split(X.values, y.values, test_size=0.2, random_state=42,)

In [114]:
X_train

array([[9.029e+00, 1.733e+01, 5.879e+01, ..., 1.750e-01, 4.228e-01,
        1.175e-01],
       [2.109e+01, 2.657e+01, 1.427e+02, ..., 2.903e-01, 4.098e-01,
        1.284e-01],
       [9.173e+00, 1.386e+01, 5.920e+01, ..., 5.087e-02, 3.282e-01,
        8.490e-02],
       ...,
       [1.429e+01, 1.682e+01, 9.030e+01, ..., 3.333e-02, 2.458e-01,
        6.120e-02],
       [1.398e+01, 1.962e+01, 9.112e+01, ..., 1.827e-01, 3.179e-01,
        1.055e-01],
       [1.218e+01, 2.052e+01, 7.722e+01, ..., 7.431e-02, 2.694e-01,
        6.878e-02]], shape=(455, 30))

In [115]:
X_train_tensor = torch.FloatTensor(X_train)
X_test_tensor = torch.FloatTensor(X_test)
y_train_tensor = torch.FloatTensor((y_train == 'M').astype(np.float32))
y_test_tensor = torch.FloatTensor((y_test == 'M').astype(np.float32))

In [116]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Using device: {device}')

Using device: cuda

In [117]:
class BreastCancerDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return len(self.features)

    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]

In [118]:
train_dataset = BreastCancerDataset(X_train_tensor, y_train_tensor)

test_dataset = BreastCancerDataset(X_test_tensor, y_test_tensor)

In [119]:
class MyNN(nn.Module):
    def __init__(self, input_size ,hidden_layer, output_size,neurons_per_layer,dropout_rate):
        super().__init__()
        layers = []
        for i in range(hidden_layer):
            layers.append(nn.Linear(input_size, neurons_per_layer))
            layers.append(nn.ReLU())
            layers.append(nn.Dropout(dropout_rate))
            input_size = neurons_per_layer
        layers.append(nn.Linear(neurons_per_layer, output_size))
        self.network = nn.Sequential(*layers)
    def forward(self,x):
        return self.network(x)

In [120]:
# objective function for Optuna
def objective(trial):
    # Hyperparameters to tune
    hidden_layer = trial.suggest_int('hidden_layer', 2, 128, step = 1)
    neurons_per_layer = trial.suggest_int('neurons_per_layer', 16, 256, step = 4)
    dropout_rate = trial.suggest_float('dropout_rate', 0.1, 0.5, step = 0.1)
    batch_size = trial.suggest_categorical('batch_size', [16, 32, 64, 128])
    optimizer_name = trial.suggest_categorical('optimizer', ['Adam','SGD','RMSprop'])
    weight_decay = trial.suggest_float('weight_decay', 1e-5, 1e-1, log=True)
    epochs = trial.suggest_int('epochs', 10,100, step = 10)
    learning_rate = trial.suggest_float('learning_rate', 1e-5, 1e-1, log=True)
    
    # model initialization
    input_size = X_train.shape[1]
    output_size = 1
    model = MyNN(input_size, hidden_layer, output_size, neurons_per_layer, dropout_rate)
    model.to(device)
    # optimizer selection
    optimizer = optim.SGD(model.parameters(), lr=0.1, weight_decay=1e-4)
    if optimizer_name == 'Adam':
        optimizer = torch.optim.Adam(model.parameters(), lr = learning_rate, weight_decay = weight_decay)
    elif optimizer_name == 'SGD':
        optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate, weight_decay = weight_decay)
    else: 
        optimizer = torch.optim.RMSprop(model.parameters(), lr = learning_rate, weight_decay = weight_decay)
    criterion = nn.BCEWithLogitsLoss()
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)
    # training loop
    model.train()
    for epoch in range(epochs):
        for batch_features, batch_labels in train_loader:
            batch_features, batch_labels = batch_features.to(device), batch_labels.to(device)
            
            outputs = model(batch_features)
            loss = criterion(outputs.squeeze(1), batch_labels)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
    # validation 
    model.eval()
    
    total = 0
    correct = 0
    with torch.no_grad():
        for batch_features, batch_labels in test_loader:
            batch_features, batch_labels = batch_features.to(device), batch_labels.to(device)
            outputs = model(batch_features.squeeze(1))
            probs = torch.sigmoid(outputs).squeeze(1)
            predicted = (probs >= 0.5).float()
            total += batch_labels.size(0)
            correct += (predicted == batch_labels).sum().item()
    accuracy = correct / total
    return accuracy

In [121]:
!pip install optuna

Requirement already satisfied: optuna in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (4.6.0)
Requirement already satisfied: alembic>=1.5.0 in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from optuna) (1.17.2)
Requirement already satisfied: colorlog in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from optuna) (6.10.1)
Requirement already satisfied: numpy in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from optuna) (2.2.6)
Requirement already satisfied: packaging>=20.0 in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from optuna) (24.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from optuna) (2.0.41)
Requirement already satisfied: tqdm in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from optuna) (6.0.2)
Requirement already satisfied: Mako in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from alembic>=1.5.0->optuna) (4.13.2)
Requirement already satisfied: greenlet>=1 in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from sqlalchemy>=1.4.2->optuna) (3.2.2)
Requirement already satisfied: colorama in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from colorlog->optuna) (0.4.6)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\users\lenovo\anaconda3\envs\test\lib\site-packages (from Mako->alembic>=1.5.0->optuna) (3.0.2)

In [122]:
import optuna

study = optuna.create_study(direction='maximize')

[I 2026-01-02 13:55:36,047] A new study created in memory with name: no-name-b615a071-80ea-4f40-94bc-5699e6112abf

In [123]:
study.optimize(objective, n_trials=20)

[I 2026-01-02 13:55:37,023] Trial 0 finished with value: 0.6228070175438597 and parameters: {'hidden_layer': 37, 'neurons_per_layer': 180, 'dropout_rate': 0.4, 'batch_size': 64, 'optimizer': 'SGD', 'weight_decay': 0.07286967139786418, 'epochs': 10, 'learning_rate': 0.010633421078675247}. Best is trial 0 with value: 0.6228070175438597.
[I 2026-01-02 13:55:44,042] Trial 1 finished with value: 0.6228070175438597 and parameters: {'hidden_layer': 85, 'neurons_per_layer': 100, 'dropout_rate': 0.1, 'batch_size': 64, 'optimizer': 'RMSprop', 'weight_decay': 0.00022592664401396712, 'epochs': 40, 'learning_rate': 0.010399827590778024}. Best is trial 0 with value: 0.6228070175438597.
[I 2026-01-02 13:55:50,093] Trial 2 finished with value: 0.6228070175438597 and parameters: {'hidden_layer': 73, 'neurons_per_layer': 28, 'dropout_rate': 0.1, 'batch_size': 32, 'optimizer': 'Adam', 'weight_decay': 4.395094686006864e-05, 'epochs': 20, 'learning_rate': 0.02131416490498168}. Best is trial 0 with value: 0.6228070175438597.
[I 2026-01-02 13:56:42,381] Trial 3 finished with value: 0.6228070175438597 and parameters: {'hidden_layer': 126, 'neurons_per_layer': 248, 'dropout_rate': 0.2, 'batch_size': 16, 'optimizer': 'SGD', 'weight_decay': 0.0001429526227529578, 'epochs': 60, 'learning_rate': 0.00010642987551113185}. Best is trial 0 with value: 0.6228070175438597.
[I 2026-01-02 13:56:58,866] Trial 4 finished with value: 0.6228070175438597 and parameters: {'hidden_layer': 85, 'neurons_per_layer': 128, 'dropout_rate': 0.2, 'batch_size': 64, 'optimizer': 'Adam', 'weight_decay': 0.006536275657924398, 'epochs': 90, 'learning_rate': 0.0878836856610911}. Best is trial 0 with value: 0.6228070175438597.
[I 2026-01-02 13:57:00,636] Trial 5 finished with value: 0.9385964912280702 and parameters: {'hidden_layer': 3, 'neurons_per_layer': 84, 'dropout_rate': 0.5, 'batch_size': 32, 'optimizer': 'RMSprop', 'weight_decay': 3.13165660377406e-05, 'epochs': 50, 'learning_rate': 0.0010870065050115377}. Best is trial 5 with value: 0.9385964912280702.
[I 2026-01-02 13:57:17,283] Trial 6 finished with value: 0.6228070175438597 and parameters: {'hidden_layer': 60, 'neurons_per_layer': 164, 'dropout_rate': 0.4, 'batch_size': 32, 'optimizer': 'SGD', 'weight_decay': 0.07872562279724653, 'epochs': 70, 'learning_rate': 0.010360476829955906}. Best is trial 5 with value: 0.9385964912280702.
[I 2026-01-02 13:58:29,587] Trial 7 finished with value: 0.6228070175438597 and parameters: {'hidden_layer': 102, 'neurons_per_layer': 128, 'dropout_rate': 0.2, 'batch_size': 32, 'optimizer': 'SGD', 'weight_decay': 0.004247056326307226, 'epochs': 100, 'learning_rate': 0.03571600740903527}. Best is trial 5 with value: 0.9385964912280702.
[I 2026-01-02 13:58:36,489] Trial 8 finished with value: 0.6228070175438597 and parameters: {'hidden_layer': 34, 'neurons_per_layer': 64, 'dropout_rate': 0.2, 'batch_size': 128, 'optimizer': 'Adam', 'weight_decay': 0.0038862916496677454, 'epochs': 50, 'learning_rate': 0.0168644585475334}. Best is trial 5 with value: 0.9385964912280702.
[I 2026-01-02 14:04:10,360] Trial 9 finished with value: 0.6228070175438597 and parameters: {'hidden_layer': 86, 'neurons_per_layer': 196, 'dropout_rate': 0.2, 'batch_size': 16, 'optimizer': 'SGD', 'weight_decay': 0.0003245810604974094, 'epochs': 80, 'learning_rate': 0.0006228316749711745}. Best is trial 5 with value: 0.9385964912280702.
[I 2026-01-02 14:04:14,416] Trial 10 finished with value: 0.6228070175438597 and parameters: {'hidden_layer': 11, 'neurons_per_layer': 16, 'dropout_rate': 0.5, 'batch_size': 128, 'optimizer': 'RMSprop', 'weight_decay': 1.6774011769824003e-05, 'epochs': 30, 'learning_rate': 2.3665478569491047e-05}. Best is trial 5 with value: 0.9385964912280702.
[I 2026-01-02 14:04:15,911] Trial 11 finished with value: 0.9298245614035088 and parameters: {'hidden_layer': 4, 'neurons_per_layer': 208, 'dropout_rate': 0.5, 'batch_size': 64, 'optimizer': 'RMSprop', 'weight_decay': 0.07077320675464029, 'epochs': 10, 'learning_rate': 0.0011007169338144746}. Best is trial 5 with value: 0.9385964912280702.
[I 2026-01-02 14:04:19,124] Trial 12 finished with value: 0.9122807017543859 and parameters: {'hidden_layer': 2, 'neurons_per_layer': 224, 'dropout_rate': 0.5, 'batch_size': 64, 'optimizer': 'RMSprop', 'weight_decay': 0.021253535272248214, 'epochs': 30, 'learning_rate': 0.0012948289544786457}. Best is trial 5 with value: 0.9385964912280702.
[I 2026-01-02 14:04:26,668] Trial 13 finished with value: 0.6228070175438597 and parameters: {'hidden_layer': 22, 'neurons_per_layer': 84, 'dropout_rate': 0.4, 'batch_size': 32, 'optimizer': 'RMSprop', 'weight_decay': 0.0010057634719272692, 'epochs': 10, 'learning_rate': 0.0010852149807716231}. Best is trial 5 with value: 0.9385964912280702.
[I 2026-01-02 14:05:44,185] Trial 14 finished with value: 0.6228070175438597 and parameters: {'hidden_layer': 48, 'neurons_per_layer': 148, 'dropout_rate': 0.5, 'batch_size': 32, 'optimizer': 'RMSprop', 'weight_decay': 0.0009023579448340365, 'epochs': 50, 'learning_rate': 0.0002255748569944131}. Best is trial 5 with value: 0.9385964912280702.
[I 2026-01-02 14:06:11,623] Trial 15 finished with value: 0.631578947368421 and parameters: {'hidden_layer': 20, 'neurons_per_layer': 212, 'dropout_rate': 0.4, 'batch_size': 64, 'optimizer': 'RMSprop', 'weight_decay': 1.010047139298319e-05, 'epochs': 70, 'learning_rate': 0.003030381212391619}. Best is trial 5 with value: 0.9385964912280702.
[I 2026-01-02 14:06:22,629] Trial 16 finished with value: 0.9473684210526315 and parameters: {'hidden_layer': 3, 'neurons_per_layer': 256, 'dropout_rate': 0.30000000000000004, 'batch_size': 16, 'optimizer': 'RMSprop', 'weight_decay': 7.820524600610245e-05, 'epochs': 30, 'learning_rate': 0.00023526953998929557}. Best is trial 16 with value: 0.9473684210526315.
[I 2026-01-02 14:07:29,867] Trial 17 finished with value: 0.6228070175438597 and parameters: {'hidden_layer': 27, 'neurons_per_layer': 52, 'dropout_rate': 0.30000000000000004, 'batch_size': 16, 'optimizer': 'RMSprop', 'weight_decay': 5.1535102533949566e-05, 'epochs': 40, 'learning_rate': 5.295541680490148e-05}. Best is trial 16 with value: 0.9473684210526315.
[I 2026-01-02 14:09:28,711] Trial 18 finished with value: 0.6228070175438597 and parameters: {'hidden_layer': 56, 'neurons_per_layer': 256, 'dropout_rate': 0.30000000000000004, 'batch_size': 16, 'optimizer': 'RMSprop', 'weight_decay': 4.604523764123416e-05, 'epochs': 30, 'learning_rate': 0.0002771856036148843}. Best is trial 16 with value: 0.9473684210526315.
[I 2026-01-02 14:11:55,388] Trial 19 finished with value: 0.6228070175438597 and parameters: {'hidden_layer': 42, 'neurons_per_layer': 104, 'dropout_rate': 0.30000000000000004, 'batch_size': 16, 'optimizer': 'RMSprop', 'weight_decay': 0.00010962915275485091, 'epochs': 60, 'learning_rate': 1.3443734994335488e-05}. Best is trial 16 with value: 0.9473684210526315.

In [124]:
study.best_params

{'hidden_layer': 3,
 'neurons_per_layer': 256,
 'dropout_rate': 0.30000000000000004,
 'batch_size': 16,
 'optimizer': 'RMSprop',
 'weight_decay': 7.820524600610245e-05,
 'epochs': 30,
 'learning_rate': 0.00023526953998929557}